name: XcraftSigns
main: de.xcraft.voronwe.XcraftSigns.XcraftSigns
version: ${pom.version}
authors:
  - Voronwe
  - MyNameIsJan
load: POSTWORLD
api-version: 1.15

depend: [XcraftLibrary]

commands:
  xcs:
    description: Sign manipulation (not implemented)
    usage: /<command> help
permissions:
  XcraftSigns.checkpoints.unlock:
    description: Access to checkpoint unlock signs (not implemented)
    default: true
  XcraftSigns.checkpoints.entry:
    description: Access to checkpoint entry signs (not implemented)
    default: true
  XcraftSigns.checkpoints.create:
    description: Access to checkpoint entry signs
    default: op
  XcraftSigns.checkpoints.heal:
    description: Access to checkpoint entry signs
    default: true
  XcraftSigns.checkpoints.spawn:
    description: Access to checkpoint entry signs
    default: true
  XcraftSigns.signs.color:
    description: Allows using colors on signs
    default: op
  XcraftSigns.signs.edit:
    description: Allows editing of signs
    default: op
